### ISSUE TITLE
Does not detect kernels with symbols

### ISSUE THREAD

**Issue by zecoxao** [SocraticBliss/ps4_kernel_loader#1]
![imagem](https://github.com/SocraticBliss/ps4_kernel_loader/assets/1857828/b1ad9fcb-c4f8-4383-88dc-cc12b7f89741)

**Comment by SocraticBliss** [comment]
For the kernels with symbols, I felt that the default ELF64 loader actually performed adequately.

If there is value added in having some of the ancillary processing performed on these kernels, I can potentially create a plugin that will perform these actions on demand, instead of being part of the loader itself.

**Comment by zecoxao** [comment]
it would be nice if it worked for both kinds of kernels, and loaded the symbols as well.
there's also an issue where loading any kind of elfs besides the kernel produces errors on ida pro when loading.

**Comment by SocraticBliss** [comment]
Issue resolved with latest commit.
